execution_engine: asyncio
logger:
  transports: [console]
  level: info

google:
  default_model: gemini-2.0-flash

openai:
  default_model: gpt-4o

mcp:
  servers:
    bitrix_crm:
      transport: stdio
      command: ./run_mcp_server.sh
      args:
        - mcp_server.py
